qPCR_data <- read.csv("mmu-miR-128-3p_M.csv", header=TRUE, sep=",",row.names=NULL,stringsAsFactors=FALSE,check.names=FALSE) #imports all data as character type.
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("NTg","HetWT","HomWT","HetMT","HomMT"))
qPCR_data$Treatment <- factor(qPCR_data$Treatment, levels=c("Vehicle","LPS"))
fit1 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit1)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetWT","NTg","HomWT","HetMT","HomMT"))
fit2 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit2)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomWT","NTg","HetWT","HetMT","HomMT"))
fit3 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit3)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetMT","NTg","HetWT","HomWT","HomMT"))
fit4 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit4)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomMT","NTg","HetWT","HomWT","HetMT"))
fit5 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit5)

qPCR_data <- read.csv("mmu-miR-128-3p_F.csv", header=TRUE, sep=",",row.names=NULL,stringsAsFactors=FALSE,check.names=FALSE) #imports all data as character type.
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("NTg","HetWT","HomWT","HetMT","HomMT"))
qPCR_data$Treatment <- factor(qPCR_data$Treatment, levels=c("Vehicle","LPS"))
fit1 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit1)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetWT","NTg","HomWT","HetMT","HomMT"))
fit2 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit2)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomWT","NTg","HetWT","HetMT","HomMT"))
fit3 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit3)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetMT","NTg","HetWT","HomWT","HomMT"))
fit4 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit4)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomMT","NTg","HetWT","HomWT","HetMT"))
fit5 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit5)

qPCR_data <- read.csv("hsa-let-7b-5p_M.csv", header=TRUE, sep=",",row.names=NULL,stringsAsFactors=FALSE,check.names=FALSE) #imports all data as character type.
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("NTg","HetWT","HomWT","HetMT","HomMT"))
qPCR_data$Treatment <- factor(qPCR_data$Treatment, levels=c("Vehicle","LPS"))
fit1 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit1)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetWT","NTg","HomWT","HetMT","HomMT"))
fit2 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit2)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomWT","NTg","HetWT","HetMT","HomMT"))
fit3 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit3)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetMT","NTg","HetWT","HomWT","HomMT"))
fit4 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit4)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomMT","NTg","HetWT","HomWT","HetMT"))
fit5 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit5)

qPCR_data <- read.csv("hsa-let-7b-5p_F.csv", header=TRUE, sep=",",row.names=NULL,stringsAsFactors=FALSE,check.names=FALSE) #imports all data as character type.
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("NTg","HetWT","HomWT","HetMT","HomMT"))
qPCR_data$Treatment <- factor(qPCR_data$Treatment, levels=c("Vehicle","LPS"))
fit1 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit1)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetWT","NTg","HomWT","HetMT","HomMT"))
fit2 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit2)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomWT","NTg","HetWT","HetMT","HomMT"))
fit3 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit3)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetMT","NTg","HetWT","HomWT","HomMT"))
fit4 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit4)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomMT","NTg","HetWT","HomWT","HetMT"))
fit5 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit5)

qPCR_data <- read.csv("mmu-miR-221-5p_M.csv", header=TRUE, sep=",",row.names=NULL,stringsAsFactors=FALSE,check.names=FALSE) #imports all data as character type.
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("NTg","HetWT","HomWT","HetMT","HomMT"))
qPCR_data$Treatment <- factor(qPCR_data$Treatment, levels=c("Vehicle","LPS"))
fit1 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit1)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetWT","NTg","HomWT","HetMT","HomMT"))
fit2 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit2)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomWT","NTg","HetWT","HetMT","HomMT"))
fit3 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit3)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetMT","NTg","HetWT","HomWT","HomMT"))
fit4 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit4)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomMT","NTg","HetWT","HomWT","HetMT"))
fit5 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit5)

qPCR_data <- read.csv("mmu-miR-221-5p_F.csv", header=TRUE, sep=",",row.names=NULL,stringsAsFactors=FALSE,check.names=FALSE) #imports all data as character type.
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("NTg","HetWT","HomWT","HetMT","HomMT"))
qPCR_data$Treatment <- factor(qPCR_data$Treatment, levels=c("Vehicle","LPS"))
fit1 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit1)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetWT","NTg","HomWT","HetMT","HomMT"))
fit2 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit2)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomWT","NTg","HetWT","HetMT","HomMT"))
fit3 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit3)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetMT","NTg","HetWT","HomWT","HomMT"))
fit4 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit4)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomMT","NTg","HetWT","HomWT","HetMT"))
fit5 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit5)

qPCR_data <- read.csv("mmu-miR-326-3p_M.csv", header=TRUE, sep=",",row.names=NULL,stringsAsFactors=FALSE,check.names=FALSE) #imports all data as character type.
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("NTg","HetWT","HomWT","HetMT","HomMT"))
qPCR_data$Treatment <- factor(qPCR_data$Treatment, levels=c("Vehicle","LPS"))
fit1 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit1)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetWT","NTg","HomWT","HetMT","HomMT"))
fit2 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit2)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomWT","NTg","HetWT","HetMT","HomMT"))
fit3 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit3)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetMT","NTg","HetWT","HomWT","HomMT"))
fit4 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit4)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomMT","NTg","HetWT","HomWT","HetMT"))
fit5 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit5)

qPCR_data <- read.csv("mmu-miR-326-3p_F.csv", header=TRUE, sep=",",row.names=NULL,stringsAsFactors=FALSE,check.names=FALSE) #imports all data as character type.
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("NTg","HetWT","HomWT","HetMT","HomMT"))
qPCR_data$Treatment <- factor(qPCR_data$Treatment, levels=c("Vehicle","LPS"))
fit1 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit1)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetWT","NTg","HomWT","HetMT","HomMT"))
fit2 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit2)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomWT","NTg","HetWT","HetMT","HomMT"))
fit3 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit3)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HetMT","NTg","HetWT","HomWT","HomMT"))
fit4 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit4)
qPCR_data$Genotype <- factor(qPCR_data$Genotype, levels=c("HomMT","NTg","HetWT","HomWT","HetMT"))
fit5 <- glm(DCq ~Treatment + Genotype + Treatment:Genotype, data=qPCR_data)
summary(fit5)

